weights_path: "./binary/weights.pickle"
variance_path: "./binary/variance.pickle"
mean_path: "./binary/mean.pickle"
scale_path: "./binary/scale.pickle"
biases_path: "./binary/biases.pickle"
output_path: "./generated"
project: "./darknet_hdl.qsf"
width: 416
channels: 3
layer_groups:
# -----------------------------------------------------------------------------
- filters: 16
  layers:
  - type: conv_layer
    parallelism: 4
    size: 3
    binary: False
    bin_input: False
    bin_output: False
  - type: max_pool_layer
    binary: False
# -----------------------------------------------------------------------------
- filters: 32
  layers:
  - type: "conv_layer"
    size: 3
    binary: True
    bin_input: False
    bin_output: False
  - type: "max_pool_layer"
    binary: False
# -----------------------------------------------------------------------------
- filters: 64
  layers:
  - type: "conv_layer"
    size: 3
    binary: True
    bin_input: False
    bin_output: False
  - type: "max_pool_layer"
    binary: False
# -----------------------------------------------------------------------------
# - filters: 128
#   layers:
#   - type: "conv_layer"
#     size: 3
#     binary: True
#     bin_input: True
#     bin_output: True
  # - type: "max_pool_layer"
  #   binary: False
# -----------------------------------------------------------------------------
# - filters: 256
#   layers:
#   - type: "conv_layer"
#     parallelism: 64
#     size: 3
#     binary: True
#     bin_input: True
#     bin_output: True
#   - type: "buffer_layer"
#     binary: True
#     scattering: 2
  # - type: "max_pool_layer"
  #   binary: True
#   - type: "buffer_layer"
#     binary: True
#     scattering: 3
# -----------------------------------------------------------------------------
# - filters: 512
#   layers:
#   - type: "conv_layer"
#     parallelism: 64
#     size: 3
#     binary: True
#     bin_input: True
#     bin_output: True
#   - type: "buffer_layer"
#     binary: True
#     scattering: 2
  # - type: "max_pool_layer"
  #   binary: True
#   - type: "buffer_layer"
#     binary: True
#     scattering: 3
# -----------------------------------------------------------------------------
#- filters: 1024
#  layers:
#  - type: "conv_layer"
#    parallelism: 8
#    size: 3
#    binary: True
#    bin_input: True
#    bin_output: True
  # - type: "buffer_layer"
  #   binary: True
  #   scattering: 1
# -----------------------------------------------------------------------------
# - filters: 256
#   layers:
#   - type: "conv_layer"
#     size: 1
#     binary: True
#     bin_input: True
#     bin_output: True
#   - type: "buffer_layer"
#     binary: True
#     scattering: 3
# -----------------------------------------------------------------------------
# - filters: 512
#   layers:
#   - type: "conv_layer"
#     size: 3
#     binary: True
#     bin_input: True
#     bin_output: True
#   - type: "buffer_layer"
#     binary: True
#     scattering: 1
# -----------------------------------------------------------------------------
# - filters: 1024
#   layers:
#   - type: "conv_layer"
#     size: 1
#     binary: True
#     bin_input: True
#     bin_output: True
#   - type: "buffer_layer"
#     binary: True
#     scattering: 3
